---
title: "Results_Resample"
date: "Due May 3, 2019"
output:
  pdf_document:
    toc: yes
  html_document:
    theme: readable
    toc: yes
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.pos = '!h', echo = F)
```

## Data Generation Functions

```{r}
genNormalPowers <- function(n, mean=0, sd=1) {
  # INPUT:
  # n is the number of teams
  
  # OUTPUT:
  # returns a vector of team powers, sorted in decreasing order
  powers <- rnorm(n, mean, sd)
  return(sort(abs(powers), decreasing=TRUE))
}

# Reference: adapted from Yuchen Li (li215), HW2, Exercise 4

acceptReject <- function(nsim, f, min, max, M) {
  # INPUT:
  # nsim is the number of simulations
  # f is the target distribution
  # min is the min value in the domain of f
  # max is the max value in the domain of f
  # max
  # M >= sup{f(x)}
  
  # OUTPUT:
  # returns a vector of random variates sampled from f, using the 
  #   Accept-Reject method with Unif(min, max) as the reference distribution
  k1 = 0             # counter for accepted samples
  j1 = 0             # number of iterations required to get desired sample size
  y1 = numeric(nsim)    # storing the sample
  while(k1 < nsim){
      u = runif(1)
      x = runif(1, min, max)  # random variate from reference distribution
      g1 = 1
      if (u < f(x) / M / g1) {
        # condition of accepting x in our sample
        k1 = k1 + 1
        y1[k1] = x
      }
      j1 = j1 + 1
  }
  return(sort(y1, decreasing=TRUE))
}

inverseCDF <- function(n, inv_cdf) {
  # INPUT:
  # n is the number of simulations
  # inv_cdf is the inverse CDF function for f
  
  # OUTPUT:
  # returns a vector of random variates sampled from PDF f,
  #   using the Inverse CDF method
  u = runif(n)
  y = numeric(n)
  for (i in 1:n) {
    y[i] = inv_cdf(u[i])
  }
  return(sort(y, decreasing=TRUE))
}

genCrossTeamWinningProbabilities <- function(powers) {
  # INPUT:
  # powers is the teams powers
  
  # OUTPUT:
  # returns an n x n matrix M where M_{ij} is the probability of team-i beating team-j
  n = length(powers)
  probs = matrix(nrow=n, ncol=n)
  for (i in 1:n) {
    for (j in 1:n) {
      probs[i,j] = powers[i] / (powers[i] + powers[j])
    }
  }
  return(probs)
}
```

## Seeding Functions

```{r}
#' Creates a traditional tournament style seeding arrangement. 
#'
#' @param size is the number of seeds to generate. This needs
#' to be a power of two.
#'
tournament_seeding = function(size) {
    
    #' Generates the next round of seeding based off the passed in round.
    #'
    #' @param seeds is the previous round of seeding to generate for.
    #'
    nextRound = function(seeds) {
        
        # Next round has twice the size
        nextSize = length(seeds) * 2
        out = numeric(nextSize)
        idx = 1
        
        # Make sure to match up best seed with worst
        for (seed in seeds) {
            out[idx] = seed
            out[idx + 1] = (nextSize + 1) - seed
            idx = idx + 2
        }
        
        return(out)
    }
    
    # Stop if not a power of two
    if (sum(as.numeric(intToBits(size))) != 1) {
        stop("Size must be a power of two")
    }
    
    # Special case when size is 2
    if (size == 2) {
        return(c(1, 2))
    }
    
    # Calculate number of rounds
    rounds = log2(size) - 1
    
    # Start with first two seeds
    seeds = c(1, 2)
    
    # Iteratively generate next seeds
    for (i in 1:rounds) {
        seeds = nextRound(seeds)
    }
    
    return(seeds)
}

#' Creates a seeding arrangement that is left skewed.
#'
#' @param size is the number of seeds to generate. This needs
#' to be a power of two.
#'
left_skewed_seeding = function(size) {
    
    # Stop if not a power of two
    if (sum(as.numeric(intToBits(size))) != 1) {
        stop("Size must be a power of two")
    }
    
    # Special case when size is 2
    if (size == 2) {
        return(c(1, 2))
    }
    
    # Create seeds and left/right branches
    seeds = 1:size
    left_seeds = numeric(size / 2)
    right_seeds = numeric(size / 2)
    
    # Indexes for the left/right branches
    left_idx = 1
    right_idx = 1
    
    # Keep track of which branch will get the next seed
    left_turn = TRUE
    
    # For each iteration add the first and last seed to the
    # current branch
    for (i in 1:(size / 2)) {
        if (left_turn) {
            left_seeds[left_idx] = seeds[i]
            left_seeds[left_idx + 1] = seeds[(size + 1) - i]
            left_idx = left_idx + 2
            left_turn = FALSE
        } else {
            right_seeds[right_idx] = seeds[i]
            right_seeds[right_idx + 1] = seeds[(size + 1) - i]
            right_idx = right_idx + 2
            left_turn = TRUE
        }
    }
    
    # Combine branches
    c(left_seeds, right_seeds)
}

#' Creates a random seeding arrangement. 
#'
#' @param size is the number of seeds to generate. This needs
#' to be a power of two.
#'
random_seeding = function(size) {
    # Stop if not a power of two
    if (sum(as.numeric(intToBits(size))) != 1) {
        stop("Size must be a power of two")
    }
    
    return(sample(1:size, size))
}
```

## Simulation Functions

```{r}
simGame <- function(teams, matchups) {
  # function to simulate a game
  
  # INPUT:
  # teams is a vector of two teams (indices) that are "playing'
  # matchups is the matchup/probability matrix
  
  # OUTPUT:
  # returns winner of game
  
  team1 <- teams[1]
  team2 <- teams[2]
  matchup <- matchups[team1, team2]
  
  if (runif(1) < matchup) {
    return(team1)
  } else {
    return(team2)
  }
}

simRound <- function(bracket, matchups) {
  # function to simulate a round of a tournament given a bracket and probability matrix
  
  # INPUT:
  # bracket is the bracket structure
  # matchups is the matchup/probability matrix
  
  # OUTPUT:
  # returns winners of the round
  
  nGames <- length(bracket)/2
  outBracket <- c()
  for (game in 1:nGames) {
    teams <- bracket[(2*game - 1):(2*game)]
    winner <- simGame(teams, matchups)
    outBracket <- c(outBracket, winner)
  }
  
  return(outBracket)
}

# want to capture number of wins each team has per tournament
# list with the winning team
# "winner = team #
# "num wins" = c(how many wins each team has gotten)

simTournament <- function(bracket, matchups) {
  # function to simulate a tournament given a bracket and probability matrix
  
  # INPUT:
  # bracket is the bracket structure
  # matchups is the matchup/probability matrix
  
  # OUTPUT:
  # returns winner of tournament
  
  nTeams <- length(bracket)
  newBracket <- bracket
  nRounds <- log2(nTeams)
  
  results = c("Winner"=-1,"WinsPerTeam"=list(rep(0, ncol(matchups))))
  
  for (round in 1:nRounds) {
    #winsPrev = results["WinsPerTeam"]
    newBracket <- simRound(newBracket, matchups)
    for(i in newBracket){
      results$WinsPerTeam[i] = results$WinsPerTeam[i]+1
    }
  }
  
  results["Winner"] = newBracket
  return(results)
}
```

## Bayesian Functions

```{r}
# get win distribution of a bracket (via simulation)
getWinDistribution <- function(bracket, matchups, nSim=10000) {
    simResults <- replicate(nSim, simTournament(bracket, matchups), simplify='array')
    winners <- numeric(nSim)
    for(i in 1:nSim) winners[i] = simResults[,i]$Winner
    out <- data.frame(table(winners))
    colnames(out) <- c("teams", "freq")
    out$teams <- as.numeric(out$teams)
    return(out)
}


# get prior and posterior win distributions of an old and new bracket
getPriorAndPosteriorWins <- function(oldBracket, newBracket, matchups, nSim=10000) {
    prior <- getWinDistribution(oldBracket, matchups, nSim)
    posterior <- getWinDistribution(newBracket, matchups, nSim)
    
    out <- prior
    colnames(out) <- c("teams", "priorFreq")
    
    nTeams <- length(oldBracket)
    for (team in 1:nTeams) {
        if (!(any(newBracket == team))) {
            tempDF <- data.frame(t(c(team, 0)))
            colnames(tempDF) <- c("teams", "freq")
            posterior <- rbind(posterior, tempDF)
        }
    }
    
    posterior <- posterior[order(posterior$teams),]
    out$postFreq <- posterior$freq
    
    return(out)
}


getExpectedWins <- function(bracket, matchups, nSim=10000) {
    simResults <- replicate(nSim, simTournament(bracket, matchups), simplify='array')
    
    winsPerTeam <- c()
    for(i in 1:nSim) winsPerTeam = rbind(winsPerTeam, simResults[,i]$WinsPerTeam)
    expWins <- apply(winsPerTeam, MARGIN=2, FUN=mean)
    sdWins <- apply(winsPerTeam, MARGIN=2, FUN=sd)
    
    teams <- 1:ncol(matchups)
    out <- data.frame(teams, expWins, sdWins)
    out$teams <- as.numeric(out$teams)
    return(out)
}


getPriorAndPosteriorExpectedWins <- function(oldBracket, newBracket, matchups, nSim=10000) {
    prior <- getExpectedWins(oldBracket, matchups, nSim)
    posterior <- getExpectedWins(newBracket, matchups, nSim)
    
    out <- prior
    colnames(out) <- c("teams", "priorExp", "priorSD")
    
    totTeams <- ncol(matchups)
    oldTeams <- length(oldBracket)
    newTeams <- length(newBracket)
    
    oldRounds <- log2(totTeams) - log2(oldTeams)
    newRounds <- log2(totTeams) - log2(newTeams)
    
    out$priorExp <- out$priorExp
    out$postExp <- posterior$expWins
    out$postSD <- posterior$sdWins
    
    for (team in 1:totTeams) {
        if (any(newBracket == team)) out$postExp[team] = out$postExp[team] + newRounds
        if (any(oldBracket == team)) out$priorExp[team] = out$priorExp[team] + oldRounds
    }
    
    return(out)
}
```

## Resampling Functions

```{r}
#function to generate bootstrap replicates
#INPUT:
#x is vector of team ranking/ other measure of 
#team power in different simulations
#B is number of replicates to generate
#estimator is the statistic we want, set as mean by
#default
#l is the length of bootstrap resample in each run
#set to length of x by default
#OUTPUT
#a list of bootstrap replicates, bias ans standard error
boot_replicate <- function(x, B = 5000, estimator = mean, l = length(x)){
  boots <- replicate(B, estimator(sample(x,l,replace=TRUE)))
  sd_b <- sd(boots)
  bias_b <- mean(boots - estimator(x))
  list(boot = boots, bias = bias_b, se = sd_b)
}

#function to generate jackknife replicates
#INPUT:
#x is vector of team ranking/ other measure of 
#team power in different simulations
#estimator is the statistic we want, set as mean by
#default
#OUTPUT
#a list of jackknife replicates, bias ans standard error
jack_replicate <- function(x, estimator = mean){
  n <- length(x)
  jack <- numeric(n)
  #perform jackknife
  for(i in 1:n)
    jack[i] <- estimator(x[-i])
  #bias using jackknife
  bias_j <- (n-1)*(mean(jack)-estimator(x))
  sumsq=sum((jack-mean(jack))^2)
  se_j <- sqrt((n-1)/n)*sqrt(sumsq)
  list(jack = jack,bias = bias_j, se = se_j)
}
```

## MLB Data

```{r}
# gl18 <- read.csv("GL2018.TXT",header = F)
# head(gl18)
# unique(gl18$V4)
# unique(gl18[,c(5,8)])
# nrow(subset(gl18,V5=='AL'&V8=='NL'))
# nrow(subset(gl18,V161!='Y'))

# data files were downloaded from 
# https://www.retrosheet.org/gamelogs/
# The information used here was obtained free of
# charge from and is copyrighted by Retrosheet.  Interested
# parties may contact Retrosheet at "www.retrosheet.org".
gl16 <- read.csv("mlb/mlb_data/GL2016.TXT",header = F)[,c(4,5,10,7,8,11)]
gl17 <- read.csv("mlb/mlb_data/GL2017.TXT",header = F)[,c(4,5,10,7,8,11)]
gl18 <- read.csv("mlb/mlb_data/GL2018.TXT",header = F)[,c(4,5,10,7,8,11)]
#simiplified game logs from 2016 to 2018
gl <- rbind(gl16,gl17,gl18)
colnames(gl) <- c('vteam','vleague','vscore','hteam','hleague','hscore')

win <- lose <- draw <- matrix(0,30,30,dimnames = 
         list(paste0(levels(gl$vteam),'v'),paste0(levels(gl$vteam),'h')))
for(i in 1:nrow(gl)){
  if(gl[i,3]>gl[i,6])
    win[gl$vteam[i],gl$hteam[i]] = win[gl$vteam[i],gl$hteam[i]]+1
  else if(gl[i,3]<gl[i,6])
    lose[gl$vteam[i],gl$hteam[i]] = lose[gl$vteam[i],gl$hteam[i]]+1
  else
    draw[gl$vteam[i],gl$hteam[i]] = draw[gl$vteam[i],gl$hteam[i]]+1
}
total <- win+lose+draw
#winning probability of visiting teams, where rows are visiting teams and 
#cols are home teams.
#For example (ANAv,CHAh) means the avg probability of ANA winning CHA as a 
#visiting team. This also means the avg probability of CHA losing or drawing
#ANA as a home team (P(lose|draw) = 1-P(win))
#NaN means there's no game records for 2 teams 
winprob.v <- win/total
#winprob.v[1:8,1:8]
# avg winnning prob not considering visiting & home
alltotal <- total*upper.tri(total) + t(total)*upper.tri(total)
alltotal <- alltotal+t(alltotal)
allwin <- win*upper.tri(win) + t(lose)*upper.tri(win) +
  win*lower.tri(win) + t(lose)*lower.tri(lose)
winprob <- allwin/alltotal
dimnames(alltotal) <- dimnames(winprob) <- list(levels(gl$vteam), levels(gl$vteam))
#total matches between 2 teams
#alltotal[1:10,1:10]
#avg winnning prob not considering visiting & home
#For example (ANA,CHA) means the avg probability of ANA winning CHA
#This matrix could be used directly in sim_tournament_initial.R
#winprob[1:9,1:9]
#names of teams 
#levels(gl$vteam)
```

## Results

```{r}
getWinners = function(results) {
    winnerList = c()
    for(i in 1:(length(results) / 2)){
        winnerList = c(winnerList,results[,i]$Winner)
    }
    return(winnerList)
}

getWinsPerTeam = function(results) {
    winsPerTeamList = c()
    for(i in 1:(length(results) / 2)){
        winsPerTeamList = rbind(winsPerTeamList,results[,i]$WinsPerTeam)
    }
    return(winsPerTeamList)
}
```

## Resample_results

```{r, echo=T}
#another version of simTournament 
#returns the final standing of teams
#for example: 2 3 1 4 
#means team2 is winner, team3 is second,...
simTournament <- function(bracket, matchups) {
  # function to simulate a tournament given a bracket and probability matrix
  
  # INPUT:
  # bracket is the bracket structure
  # matchups is the matchup/probability matrix
  
  # OUTPUT:
  # final standing of teams
  
  nTeams <- length(bracket)
  newBracket <- bracket
  nRounds <- log2(nTeams)
  
  #results = c("Winner"=-1,"WinsPerTeam"=list(rep(0, ncol(matchups))))
  results <- numeric(nTeams)
  
  for (round in 1:nRounds) {
    #winsPrev = results["WinsPerTeam"]
    oldBracket <- newBracket
    newBracket <- simRound(newBracket, matchups)
    results[(2^(nRounds-round)+1):2^(nRounds-round+1)] <- 
      setdiff(oldBracket,newBracket)
  }
  
  results[1] <- newBracket
  return(results)
}



#INPUT: x is index of the team
#       res is simulation results
#OUTPUT: rank of x in simulations
getRank <- function(x, res, lower = T){
  n <- length(res)
  rank <- numeric(n)
  for(i in 1:n){
    roughrank <- which(res[[i]]==x)
    if(roughrank == 2 | roughrank == 1)
      rank[i] <- roughrank
    #pick lowest rank for a range of rank
    #for example, if rank is 5th-8th, let rank be 8
    else if(lower == T)
      rank[i] <- 2^ceiling(log2(roughrank))
    #if lower = F pick highest rank in range
    else 
      rank[i] <- 2^floor(log2(roughrank))+1
  }
  rank
}
```


```{r,echo=T}
numTeams = 8
nSim = 1000

#set.seed(428)
power <- genNormalPowers(numTeams)
prob = genCrossTeamWinningProbabilities(power)
#with random seeding
res = replicate(nSim, simTournament(
  sample(1:numTeams), prob),simplify = FALSE)
#ranks of each team
ranks <- lapply(1:numTeams, getRank, res = res)
#bootstrap estimation on mean of ranks of each team
mean_boot <- lapply(ranks, boot_replicate)
#a box plot of ranking of each team
mean_boot_raw <- lapply(mean_boot, function(x) x$boot)
boxplot(mean_boot_raw)
```

```{r,echo=T}
#with seeding
seeds = tournament_seeding(numTeams)
res = replicate(nSim, simTournament(seeds, prob), simplify = FALSE)
#ranks of each team
ranks <- lapply(1:numTeams, getRank, res = res)
#bootstrap estimation on mean of ranks of each team
mean_boot <- lapply(ranks, boot_replicate)
#a box plot of ranking of each team
mean_boot_raw <- lapply(mean_boot, function(x) x$boot)
boxplot(mean_boot_raw)
```

## Some NLB
```{r, echo = T, cache = T}
nSim = 1000
#add 2 dummy team as there're 30 teams in NLB
numTeams <- 32
prob <- cbind(rbind(winprob,numeric(30),numeric(30)),rep(1.,32),rep(1.,32))
prob[32,31] <- 0

res = replicate(nSim, simTournament(
  sample(1:numTeams), prob),simplify = FALSE)
#ranks of each team
ranks <- lapply(1:numTeams, getRank, res = res)
#bootstrap estimation on mean of ranks of each team
mean_boot <- lapply(ranks, boot_replicate)
#a box plot of ranking of each team
mean_boot_raw <- lapply(mean_boot, function(x) x$boot)
names(mean_boot_raw) <- dimnames(prob)[[1]]
```

```{r, echo = T, fig.height=10}
boxplot(mean_boot_raw,horizontal = T, las = 1)
```

